### ISSUE TITLE
No obvious way to create first Admin user

### ISSUE THREAD

**Issue by jimlesch** [zakaria-chahboun/my-shopping-cart-project#1]
Hey great work Zakaria! I had downloaded your project to learn and ran into a few problems getting it to run, which I thought I should share back with you in appreciation for you sharing all this code.  First, getting started with the project I could not from the web GUI create an admin user.  I ended up modifying the account sign up page to create an admin user temporarily so I could then easily add categories.

Expected: Script to create initial admin user to login?

Sorry if I missed something in instructions.

**Comment by zakaria-chahboun** [comment]
Hi !
you have to create a <b> " collection " </b>  in MongoDB for Admin called " <b> admin </b> "
it have some fields like "<b>  name, password, email, ....</b> " in the same database " <b> market</b> "
look this Model 

https://github.com/zakaria-chahboun/my-shopping-cart-project/blob/master/models/admin.js
