### ISSUE TITLE
After creating a few categories for the first time, the "Load Categories" arrow does not load them

### ISSUE THREAD

**Issue by jimlesch** [zakaria-chahboun/my-shopping-cart-project#2]
From a new project as the initial admin user (no product or category data created yet), Create 2 categories (I created "meat" and "vegetables".  On the same products screen, after creating the categories, try clicking "load categories".

Actual behavior: Nothing new loads into the drop down.
Expected behavior: new categories load into the categories drop down.

**Comment by zakaria-chahboun** [comment]
<img  src="http://i.imgur.com/DzZvkWI.png" />

first step : create your category
second step : load your category
third step : chose your category

:)
